version: '3.8'
services:
  db-auth:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-nest

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
